CREATE TABLE t_group
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_t_group PRIMARY KEY (id)
);

CREATE TABLE t_group_subject
(
    group_id   BIGINT NOT NULL,
    subject_id BIGINT NOT NULL
);

CREATE TABLE t_permissions
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_t_permissions PRIMARY KEY (id)
);

CREATE TABLE t_student
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name VARCHAR(255),
    age       INTEGER                                 NOT NULL,
    group_id  BIGINT,
    CONSTRAINT pk_t_student PRIMARY KEY (id)
);

CREATE TABLE t_subject
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    teacher VARCHAR(255),
    length  INTEGER                                 NOT NULL,
    CONSTRAINT pk_t_subject PRIMARY KEY (id)
);

CREATE TABLE t_users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_t_users PRIMARY KEY (id)
);

CREATE TABLE t_users_permissions
(
    user_id        BIGINT NOT NULL,
    permissions_id BIGINT NOT NULL
);

ALTER TABLE t_student
    ADD CONSTRAINT FK_T_STUDENT_ON_GROUP FOREIGN KEY (group_id) REFERENCES t_group (id);

ALTER TABLE t_group_subject
    ADD CONSTRAINT fk_tgrosub_on_group FOREIGN KEY (group_id) REFERENCES t_group (id);

ALTER TABLE t_group_subject
    ADD CONSTRAINT fk_tgrosub_on_subject FOREIGN KEY (subject_id) REFERENCES t_subject (id);

ALTER TABLE t_users_permissions
    ADD CONSTRAINT fk_tuseper_on_permission FOREIGN KEY (permissions_id) REFERENCES t_permissions (id);

ALTER TABLE t_users_permissions
    ADD CONSTRAINT fk_tuseper_on_user FOREIGN KEY (user_id) REFERENCES t_users (id);